import NavigationBar from '@/components/Navigation/NavigationBar'
import './globals.css'
import { Roboto, Lato } from 'next/font/google'


const lato = Lato({
  weight: ['100', '300', '400', '700', '900'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lato.className} animate-text bg-gradient-to-r from-neutral-900 via-zinc-800 to-stone-800`}>
        <NavigationBar />
        {children}
        </body>
    </html>
  )
}
